### ISSUE TITLE
Allow JSON in .run()

### ISSUE THREAD

**Issue by dzwillia** [flexiodata/flexio-sdk-js#1]
Just a reminder issue to make sure it is possible to pass raw JSON (and not just a FormData object) as the part of the first parameter of the .run() call. Also make sure it is documented -- e.g. is it { formdata: ... }, or { data: ... }, etc.

**Comment by dzwillia** [comment]
I think you've unified the methodology for this. Can we close this now?

**Comment by biwillia** [comment]
It's now possible. This has been thoroughly addressed and is in the SDK test suite.
