### ISSUE TITLE
Remove `eid` from JSON in toCode() calls

### ISSUE THREAD

**Issue by dzwillia** [flexiodata/flexio-sdk-js#10]
Eids are probably going to go away in tasks at some point, but if you could omit the eid from all task toCode() calls where you return JSON (connect, email, etc.), that would be great.

![no-eid](https://user-images.githubusercontent.com/1385356/39962714-8bb4fa0a-5625-11e8-827a-5f5ed556899b.png)

**Comment by biwillia** [comment]
Fixed
