### ISSUE TITLE
Object references need to be killed to avoid outside mutation

### ISSUE THREAD

**Issue by dzwillia** [flexiodata/flexio-sdk-js#4]
In the following code the object that is passed to the Javascript SDK via something like this `Flexio.pipe(my_task_obj).toCode()` is being copied instead of deep cloned. This keeps the object reference open, which causes any mutation to that object in the Javascript SDK (such as `delete params['op']`) to propagate back to code which called the Javascript SDK.

https://github.com/flexiodata/flexio-sdk-js/blob/475e3dd7adc4769a9e02c96da4c1a7cbdfe54a38/src/pipe.js#L221-L223

**Comment by dzwillia** [comment]
Thanks. This is the biggest issue I need fixed. Right now anytime I call `Flexio.pipe(...).toCode()` in the webapp code, I am doing the clone deep myself. It's in about 15 places in my code, so it'll be nice to have that fixed.

I thought about doing it myself, but I figured I'd go this route instead.

**Comment by biwillia** [comment]
Fixed
